This is makeindex, version 2.15 [TeX Live 2020/W32TeX] (kpathsea + Thai support).
Scanning style file ./ausarbeitung/diss.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file ausarbeitung/diss.acn....done (10 entries accepted, 0 rejected).
Sorting entries....done (30 comparisons).
Generating output file ausarbeitung/diss.acr....done (14 lines written, 0 warnings).
Output written in ausarbeitung/diss.acr.
Transcript written in ausarbeitung/diss.alg.
